version: "3"
services:
  # Backend
  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/github_search_app:delegated
    ports:
      - "3000:3000"


